# Numpy и матричная алгебра

In [1]:
import numpy as np

## Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [58]:
N = 10
a = np.arange(0, N)
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [39]:
N = 9
a = np.diag(np.arange(N), k=0)
a

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8]])

In [40]:
a.diagonal()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [41]:
a.diagonal().sum()

36

## Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [48]:
from numpy import linalg

In [49]:
# коэффициенты при переменных в левой части уравнения

a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4]])


In [50]:
# значения в правой части уравнения

b = np.array( [4, 12, -3] )


In [51]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [56]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

In [57]:
4 * 0.46666667 + 2 * 3.84444444 -5.55555556

4.0